[target.thumbv7em-none-eabihf]
# Explicitly tell hf2 to look for 0x2886 (Seeed) and 0x8045 (Bootloader)
runner = "hf2 --vid 0x2886 --pid 0x8045 elf"
# runner = "elf2uf2-rs --deploy --family-id 0xADA52840"

rustflags = ["-C", "link-arg=-Tlink.x", "-C", "link-arg=-Map=xiao_blinky.map"]

[build]
target = "thumbv7em-none-eabihf"